Added AuthService and User entity
aleksandr-hrankin/project-cinema pull request #3
Opened 2020-10-07 15:07 UTC by aleksandr-hrankin

2020-10-07 15:16 UTC, KostiantynVorobiov requested changes
Good job!

2020-10-07 15:16 UTC, KostiantynVorobiov commented on src/main/java/ua/mate/cinema/service/security/AuthenticationServiceImpl.java
> +            if (user.getPassword().equals(hashPassword)) {
Можно все написать в одном if через амперсант

2020-10-08 07:01 UTC, Sofasmile commented on src/main/java/ua/mate/cinema/dao/impl/UserDaoImpl.java
> +            throw new DataProcessingException("Can't add user with ID " + user.getId(), e);
with ID " + user.getId() ????

2020-10-08 14:04 UTC, Sofasmile approved these changes

2020-10-09 13:37 UTC, merged