Added Order, User, ShoppingCart controllers
aleksandr-hrankin/project-cinema pull request #9
Opened 2020-10-26 17:56 UTC by aleksandr-hrankin

2020-10-26 19:38 UTC, IrynaDim approved these changes

2020-10-27 09:34 UTC, KseniiaMakarova requested changes

2020-10-27 09:34 UTC, KseniiaMakarova commented on src/main/java/ua/antibyte/cinema/controller/Inject.java
> +        return "inject";
```suggestion
        return "data was successfully injected";
```

2020-10-27 09:34 UTC, KseniiaMakarova commented on src/main/java/ua/antibyte/cinema/controller/OrderController.java
> +    @GetMapping("/by-userId")
```suggestion
    @GetMapping
```

2020-10-27 09:34 UTC, KseniiaMakarova commented on src/main/java/ua/antibyte/cinema/controller/ShoppingCartController.java
> +    private final ShoppingCartMapper shoppingCartMapping;
```suggestion
    private final ShoppingCartMapper shoppingCartMapper;
```

2020-10-27 09:34 UTC, KseniiaMakarova commented on src/main/java/ua/antibyte/cinema/model/dto/ShoppingCartResponseDto.java
> +    private Long userId;
aren't id and userId the same?

2020-10-27 09:34 UTC, KseniiaMakarova commented on src/main/java/ua/antibyte/cinema/service/security/AuthenticationServiceImpl.java
> +        User user = userService.findByEmail(email);
the problem is that previously, if user entered incorrect email, the AuthenticationException was thrown, and now - NoSuchElementException

I would suggest rather to call optional.get() in UserController
what do you think?

2020-10-27 11:40 UTC, KseniiaMakarova approved these changes

2020-10-28 10:56 UTC, merged